#!/home/fanweiwei/.virtualenvs/cv/bin/python3

"""
Mercury Blast


Usage:
  mercury-blast [-h | --help]
  mercury-blast --version
  mercury-blast train
  mercury-blast spinup
  mercury-blast nuke

"""

#from clint.textui import colored, puts, indent
from docopt import docopt

import spinup
import train

if __name__ == '__main__':
    arguments = docopt(__doc__, version='Mercury Blast 1.0')

    if arguments['spinup']:
        spinup.run()

    if arguments['train']:
        train.run()
